### PR TITLE
fix: ensure proper resolve condition set for vitest env

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description

Ensure `browser` export condition is configured when in `test` mode and targeting a dom environment.

## Motivation and Context

Workaround for https://github.com/vitest-dev/vitest/issues/2603 which causes the incorrect Marko runtime to be loaded in the brower env for that test runner.

## Checklist:

- [ ] I have updated/added documentation affected by my changes.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by vwong** [comment]
@DylanPiercey Ok, so how do I use this workaround? I updated to 3.0.1, and the following still gives me `TypeError: _marko_registerComponent is not a function`:

```
// @vitest-environment jsdom

import { fireEvent, render } from "@marko/testing-library";
import { describe, expect, it } from "vitest";
import template from "./index.test.marko";

describe("<my-component/>", () => {
  it("does stuff", async () => {
    const { getByLabelText } = await render(template);
    const input = getByLabelText("the-label") as HTMLInputElement;

    await fireEvent.input(input, "form-input");
  });
});
```

It doesn't matter what is in the template, even a blank file.

**Comment by DylanPiercey** [comment]
@vwong can you ensure you're on the latest version of everything and that the vitest cache is cleared at `./node_modules/.vitest`?

**Comment by DylanPiercey** [comment]
Ah dang I think I see the issue. It's that you're using comments to define the test environment. My work around only works if the environment is configured in your vite/vitest config.

**Comment by vwong** [comment]
Ah yes of course, now the change makes more sense. So, to handle a mix of `node` and `jsdom` tests, I have to run vitest twice with different config each time, right?

**Comment by vwong** [comment]
Thanks, works a charm now!

**Pull request merged**
